<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
  <?php echo $this->headScript()->setFile('/js/bootstrap.min.js') ?>
  <?php echo $this->headScript()->setFile('/js/jquery-1.11.3.min.js') ?>
</head>
<body>

<?php echo $this->layout()->content ?>
 
</body>
</html>
